"""Educational script generation service.

This module orchestrates script generation for educational videos.
Duration-based logic is preserved via section blueprints and scene targets.
Script scenes are generated by OpenAI and validated as JSON.
"""

from __future__ import annotations

import json
import logging
import re
from typing import Any

logger = logging.getLogger(__name__)

from pydantic import BaseModel, Field, ValidationError

from services.groq_service import generate_script as generate_groq_script
from services.scene_converter import DURATION_SECONDS, SCENE_TARGETS, format_scenes_as_script
from services.section_builders import DURATION_BLUEPRINTS

AUDIENCE_LABELS = {
    "school": "School",
    "college": "College",
    "professional": "Professional",
    "ug": "College",
    "pg": "Professional",
}

AUDIENCE_PROFILES = {
    "school": {
        "label": "School students (Ages 10-15)",
        "tone": "friendly, enthusiastic, clear, and engaging, with simple everyday analogies",
        "complexity": "simple vocabulary, basic concepts, no advanced or unexplained jargon",
        "visual_prompt_style": "bright colors, animated/cartoon illustrations, simple real-world object drawings, and friendly diagrams"
    },
    "college": {
        "label": "College / Undergraduate university students",
        "tone": "academic yet accessible, professional, structured, and informative",
        "complexity": "standard university-level concepts, using precise technical terminology and defining key frameworks",
        "visual_prompt_style": "clean flowcharts, textbook-style illustrations, standard process diagrams, and clear slides with bullet points"
    },
    "professional": {
        "label": "Industry professionals, specialists, and advanced researchers",
        "tone": "scholarly, analytical, authoritative, serious, and direct",
        "complexity": "advanced theoretical depth, industry-standard metrics, mathematical/scientific formulations, and critical analysis of concepts",
        "visual_prompt_style": "complex data plots, scientific charts, formal molecular/structural blueprints, technical schematics, and clean modern data overlays"
    }
}


def get_audience_profile(audience: str) -> dict:
    """Map audience key to its specific descriptive profile."""
    aud = audience.lower().strip()
    if "school" in aud:
        return AUDIENCE_PROFILES["school"]
    elif "college" in aud or "ug" in aud:
        return AUDIENCE_PROFILES["college"]
    elif "professional" in aud or "pg" in aud:
        return AUDIENCE_PROFILES["professional"]
    else:
        return AUDIENCE_PROFILES["school"]


DURATION_LABELS = {
    "1": "1 minute",
    "3": "3 minutes",
    "5": "5 minutes",
    "10": "10 minutes",
}

LANGUAGE_LABELS = {
    "english": "English",
    "hindi": "Hindi",
    "telugu": "Telugu",
}


class SceneModel(BaseModel):
    scene_number: int = Field(..., ge=1)
    duration_seconds: int = Field(..., ge=1)
    visual_prompt: str = Field(..., min_length=1)
    voiceover: str = Field(..., min_length=1)


class StructuredScriptModel(BaseModel):
    title: str = Field(..., min_length=1)
    duration: str = Field(..., min_length=1)
    scenes: list[SceneModel] = Field(..., min_length=1)


def generate_script(
    topic: str,
    audience: str,
    duration: str,
    language: str,
) -> dict:
    """Generate an educational video script from the given inputs."""
    return _build_openai_script(
        topic=topic.strip(),
        audience=audience.lower(),
        duration=duration.lower(),
        language=language.lower(),
    )


def count_words(text: str) -> int:
    """Helper to count words in a string."""
    return len(re.findall(r"\b\w+\b", text))


def _build_openai_script(
    topic: str,
    audience: str,
    duration: str,
    language: str,
) -> dict:
    """Generate a duration-aware script using Groq."""
    normalized_duration = duration if duration in DURATION_BLUEPRINTS else "3"
    duration_label = DURATION_LABELS.get(normalized_duration, f"{duration} minutes")
    target_scene_count = SCENE_TARGETS.get(normalized_duration, 11)
    target_total_seconds = DURATION_SECONDS.get(normalized_duration, 180)
    profile = get_audience_profile(audience)

    # 2.2 words per second minimum speech rate target
    min_words = int(target_total_seconds * 2.2)
    words_per_scene = int(min_words / target_scene_count)

    prompt = f"""
Create an educational video script.

Topic: {topic}
Audience Level: {profile["label"]}
Explanation Complexity: {profile["complexity"]}
Narration Tone/Voice: {profile["tone"]}
Visual Presentation Style: {profile["visual_prompt_style"]}
Language: {language}

Duration and Pacing Requirements:
- You must generate EXACTLY {target_scene_count} scenes.
- The sum of all scene durations (duration_seconds) must equal EXACTLY {target_total_seconds} seconds.
- Spoken length constraint: To prevent the video from being too short, the total combined word count of all scene voiceovers must be at least {min_words} words.
- Each scene's voiceover must be detailed, descriptive, and contain at least {words_per_scene} words. Do not keep them brief.
- Pacing: The duration_seconds for each scene should match the length of its voiceover (about 2.5 words per second). For example, a 10-second scene should contain approximately 25 words of voiceover. Ensure scene durations are proportional to the amount of content spoken.

Audience and Style Rules:
- Narration voiceover text must strictly match the "Explanation Complexity" and "Narration Tone/Voice" defined above.
- Visual prompts must describe scene compositions matching the "Visual Presentation Style" (e.g. animated cartoons for school, clean diagrams for college, and formal data charts or blueprints for professionals).
- Avoid generic visuals. All visual prompts should illustrate concrete examples of "{topic}".

Return ONLY valid JSON.

Format:
{{
"title": "Educational Video: {topic}",
"duration": "{duration_label}",
"scenes": [
  {{
    "scene_number": 1,
    "duration_seconds": 15,
    "visual_prompt": "Description of the visual following the visual presentation style rules",
    "voiceover": "Narration text spoken for this scene (in {language}, matching the target complexity)"
  }}
]
}}
"""

    max_retries = 2
    raw_response = ""
    validated_script = None

    for attempt in range(max_retries + 1):
        try:
            logger.info("Calling Groq script writer (attempt %d)...", attempt + 1)
            raw_response = generate_groq_script(prompt)
            validated_script = parse_and_validate_script_json(raw_response)
            
            total_words = sum(count_words(scene.get("voiceover", "")) for scene in validated_script.get("scenes", []))
            logger.info("Generated script has %d words (target minimum: %d words)", total_words, min_words)
            
            if total_words >= min_words:
                break  # Meets requirements
            
            if attempt < max_retries:
                prompt += f"\n\nWARNING: Your previous response was too short. The total word count was only {total_words} words, which fails our duration requirements (needed at least {min_words} words). Please regenerate the script and make the voiceover text for each scene significantly longer and more detailed (each scene voiceover must contain at least {words_per_scene} words)."
                logger.warning("Generated voiceover is too short (%d words). Retrying to extend length...", total_words)
        except Exception as e:
            logger.error("Failed script generation attempt %d: %s", attempt + 1, e)
            if attempt == max_retries:
                raise e

    if validated_script is None:
        raise ValueError("Failed to generate and validate script JSON after maximum retries.")

    validated_script["scenes"] = _normalize_scene_durations(
        validated_script["scenes"],
        DURATION_SECONDS.get(normalized_duration, DURATION_SECONDS["3"]),
    )
    validated_script["duration"] = duration_label

    sections = _derive_sections_from_scenes(
        scenes=validated_script["scenes"],
        duration=normalized_duration,
    )
    introduction = sections[0]["content"] if sections else ""
    conclusion = _extract_conclusion(sections)

    script_text = format_scenes_as_script(
        title=validated_script["title"],
        duration=validated_script["duration"],
        scenes=validated_script["scenes"],
    )

    return {
        **validated_script,
        "introduction": introduction,
        "sections": sections,
        "conclusion": conclusion,
        "script": script_text,
        "metadata": {
            "topic": topic,
            "audience": AUDIENCE_LABELS.get(audience, audience),
            "duration": duration_label,
            "language": LANGUAGE_LABELS.get(language, language),
            "section_count": len(sections),
            "scene_count": len(validated_script["scenes"]),
            "provider": "groq",
        },
    }


def parse_and_validate_script_json(
    raw_response: str,
    fallback: dict[str, Any] | None = None,
    max_retries: int = 2,
) -> dict[str, Any]:
    """Parse, clean, and validate structured script JSON."""
    last_error: Exception | None = None

    for attempt in range(max_retries + 1):
        try:
            cleaned = clean_json_response(raw_response, aggressive=attempt > 0)
            payload = json.loads(cleaned)
            validated = StructuredScriptModel.model_validate(payload)
            return validated.model_dump()
        except (json.JSONDecodeError, ValidationError, TypeError) as error:
            last_error = error

    if fallback is not None:
        try:
            validated_fallback = StructuredScriptModel.model_validate(fallback)
            return validated_fallback.model_dump()
        except ValidationError as error:
            last_error = error

    raise ValueError(f"Invalid structured script JSON: {last_error}")


def clean_json_response(raw_response: str, aggressive: bool = False) -> str:
    """Extract and normalize JSON from a raw model response."""
    text = raw_response.strip()

    if text.startswith("```"):
        text = re.sub(r"^```(?:json)?\s*", "", text)
        text = re.sub(r"\s*```$", "", text)

    start = text.find("{")
    end = text.rfind("}")
    if start != -1 and end != -1 and end > start:
        text = text[start : end + 1]

    if aggressive:
        text = text.replace("\n", " ")
        text = re.sub(r",\s*}", "}", text)
        text = re.sub(r",\s*]", "]", text)

    return text.strip()


def _normalize_scene_durations(
    scenes: list[dict[str, Any]],
    total_seconds: int,
) -> list[dict[str, Any]]:
    """Ensure scene durations are positive, respect generated proportions, and sum to total_seconds."""
    if not scenes:
        return scenes

    scene_count = len(scenes)

    def fallback_equal_distribution():
        base = total_seconds // scene_count
        remainder = total_seconds % scene_count
        durations = []
        for index in range(scene_count):
            durations.append(max(1, base + (1 if index < remainder else 0)))
        return durations

    try:
        suggested_durations = []
        for scene in scenes:
            dur = scene.get("duration_seconds")
            if dur is None:
                raise ValueError("duration_seconds is missing in scene data")
            val = int(dur)
            if val <= 0:
                raise ValueError("duration_seconds must be positive")
            suggested_durations.append(val)

        suggested_sum = sum(suggested_durations)
        if suggested_sum <= 0:
            raise ValueError("sum of suggested durations must be positive")

        # Proportional scaling
        scaled_durations = []
        for dur in suggested_durations:
            scaled = round((dur / suggested_sum) * total_seconds)
            scaled_durations.append(max(1, scaled))

        # Adjust rounding discrepancies
        current_sum = sum(scaled_durations)
        diff = total_seconds - current_sum

        if diff != 0:
            step = 1 if diff > 0 else -1
            abs_diff = abs(diff)
            for i in range(abs_diff):
                idx = i % scene_count
                scaled_durations[idx] = max(1, scaled_durations[idx] + step)

        durations = scaled_durations

    except (ValueError, TypeError) as error:
        logger.warning(
            "Suggested scene durations were invalid or missing. Falling back to equal distribution. Error: %s",
            error,
        )
        durations = fallback_equal_distribution()

    normalized: list[dict[str, Any]] = []
    for index, scene in enumerate(scenes):
        normalized.append(
            {
                **scene,
                "scene_number": index + 1,
                "duration_seconds": durations[index],
            }
        )

    return normalized


def _derive_sections_from_scenes(
    scenes: list[dict[str, Any]],
    duration: str,
) -> list[dict[str, str]]:
    """Map generated scenes back to duration blueprint sections for compatibility."""
    blueprint = DURATION_BLUEPRINTS.get(duration, DURATION_BLUEPRINTS["3"])
    if not scenes:
        return [{"title": title, "content": ""} for _, title in blueprint]

    sections: list[dict[str, str]] = []
    scene_count = len(scenes)

    for index, (_, title) in enumerate(blueprint):
        start = (index * scene_count) // len(blueprint)
        end = ((index + 1) * scene_count) // len(blueprint)
        grouped_scenes = scenes[start:end] or [scenes[min(start, scene_count - 1)]]
        content = " ".join(
            scene.get("voiceover", "").strip()
            for scene in grouped_scenes
            if scene.get("voiceover", "").strip()
        )
        sections.append({"title": title, "content": content})

    return sections


def _extract_conclusion(sections: list[dict[str, str]]) -> str:
    """Return the closing section content when present."""
    if not sections:
        return ""

    closing_titles = {"summary", "conclusion"}
    last_section = sections[-1]
    if last_section["title"].lower() in closing_titles:
        return last_section["content"]

    return last_section["content"]
