import os

file_path = r"C:\Users\G.Bharath yadav\OneDrive\Desktop\AI Video Generator\backend\main.py"

with open(file_path, "r", encoding="utf-8") as f:
    lines = f.readlines()

new_content = []
for line in lines:
    if "# ------------------------------------------------------------" in line:
        # We stop at the Library endpoint section
        break
    new_content.append(line)

new_content.append("# ------------------------------------------------------------\n")
new_content.append("# Library endpoint\n")
new_content.append("# ------------------------------------------------------------\n")
new_content.append("from services.metadata_store import delete_record\n")
new_content.append("from services.thumbnail_extractor import extract_thumbnail\n")
new_content.append("\n")
new_content.append("@app.get(\"/api/library\")\n")
new_content.append("async def get_library():\n")
new_content.append("    \"\"\"Return list of stored video metadata records.\"\"\"\n")
new_content.append("    return {\"videos\": list_records()}\n")
new_content.append("\n")
new_content.append("@app.delete(\"/api/library/{video_id}\")\n")
new_content.append("async def delete_library_video(video_id: int):    \n")
new_content.append("    records = list_records()\n")
new_content.append("    record_to_delete = next((r for r in records if r[\"id\"] == video_id), None)\n")
new_content.append("    if not record_to_delete:\n")
new_content.append("        raise HTTPException(status_code=404, detail=\"Video not found\")\n")
new_content.append("    static_dir = Path(__file__).resolve().parent / \"static\"\n")
new_content.append("    def safe_delete(file_url: str):\n")
new_content.append("        if not file_url: return\n")
new_content.append("        url_path = file_url.replace(\"/static/\", \"\")\n")
new_content.append("        file_path = static_dir / url_path\n")
new_content.append("        try:\n")
new_content.append("            if \"generated\" in str(file_path) and file_path.exists():\n")
new_content.append("                file_path.unlink()\n")
new_content.append("        except Exception as e:\n")
new_content.append("            logging.error(f\"Failed to delete {file_path}: {e}\")\n")
new_content.append("    safe_delete(record_to_delete.get(\"video_path\"))\n")
new_content.append("    safe_delete(record_to_delete.get(\"thumbnail_path\"))\n")
new_content.append("    safe_delete(record_to_delete.get(\"subtitle_path\"))\n")
new_content.append("    if record_to_delete.get(\"video_path\"):\n")
new_content.append("        base_url = record_to_delete[\"video_path\"].rsplit(\".\", 1)[0]\n")
new_content.append("        for ext in [\".srt\", \".vtt\", \".ass\"]:\n")
new_content.append("            safe_delete(base_url + ext)\n")
new_content.append("    success = delete_record(video_id)\n")
new_content.append("    if not success:\n")
new_content.append("        raise HTTPException(status_code=500, detail=\"Failed to delete database record\")\n")
new_content.append("    return {\"message\": \"Video deleted successfully\"}\n")
new_content.append("\n")
new_content.append("@app.post(\"/api/library/save\")\n")
new_content.append("async def save_to_library(payload: dict):\n")
new_content.append("    try:\n")
new_content.append("        video_url = payload.get(\"video_url\")\n")
new_content.append("        if not video_url:\n")
new_content.append("            raise HTTPException(status_code=400, detail=\"Missing video_url in payload\")\n")
new_content.append("        existing = list_records()\n")
new_content.append("        for record in existing:\n")
new_content.append("            if record.get(\"video_path\") == video_url:\n")
new_content.append("                raise HTTPException(status_code=400, detail=\"This video is already in your library.\")\n")
new_content.append("        static_dir = Path(__file__).resolve().parent / \"static\"\n")
new_content.append("        url_path = video_url.replace(\"/static/\", \"\")\n")
new_content.append("        video_path_obj = static_dir / url_path\n")
new_content.append("        file_size = 0\n")
new_content.append("        if video_path_obj.exists():\n")
new_content.append("            file_size = video_path_obj.stat().st_size\n")
new_content.append("        metadata = payload.get(\"metadata\", {})\n")
new_content.append("        duration_val = payload.get(\"duration\") or metadata.get(\"duration\", 0)\n")
new_content.append("        try:\n")
new_content.append("            duration_int = int(float(duration_val))\n")
new_content.append("        except (ValueError, TypeError):\n")
new_content.append("            duration_int = 0\n")
new_content.append("        thumb_name = video_path_obj.stem + \"_thumb.jpg\"\n")
new_content.append("        thumb_path_obj = video_path_obj.parent / thumb_name\n")
new_content.append("        if not thumb_path_obj.exists() and video_path_obj.exists():\n")
new_content.append("            try:\n")
new_content.append("                extract_thumbnail(video_path_obj, thumb_path_obj)\n")
new_content.append("            except Exception as e:\n")
new_content.append("                logging.error(f\"Thumbnail generation failed during save: {e}\")\n")
new_content.append("        if thumb_path_obj.exists():\n")
new_content.append("            thumbnail_url = video_url.rsplit(\".\", 1)[0] + \"_thumb.jpg\"\n")
new_content.append("        else:\n")
new_content.append("            thumbnail_url = None\n")
new_content.append("        record = {\n")
new_content.append("            \"title\": payload.get(\"title\", metadata.get(\"topic\", \"Untitled\")),\n")
new_content.append("            \"created_at\": datetime.datetime.utcnow().isoformat() + \"Z\",\n")
new_content.append("            \"duration\": duration_int,\n")
new_content.append("            \"presenter_type\": metadata.get(\"presenter_type\", \"none\"),\n")
new_content.append("            \"voice\": metadata.get(\"voice\", \"alloy\"),\n")
new_content.append("            \"language\": metadata.get(\"language\", \"english\"),\n")
new_content.append("            \"file_size\": file_size,\n")
new_content.append("            \"resolution\": \"1080x1920\",\n")
new_content.append("            \"thumbnail_path\": thumbnail_url,\n")
new_content.append("            \"video_path\": video_url,\n")
new_content.append("            \"subtitle_path\": payload.get(\"subtitle_url\"),\n")
new_content.append("            \"status\": \"completed\"\n")
new_content.append("        }\n")
new_content.append("        add_record(record)\n")
new_content.append("        return {\"message\": \"Video saved successfully\", \"record\": record}\n")
new_content.append("    except HTTPException:\n")
new_content.append("        raise\n")
new_content.append("    except Exception as e:\n")
new_content.append("        raise HTTPException(status_code=500, detail=str(e))\n")

with open(file_path, "w", encoding="utf-8") as f:
    f.writelines(new_content)
